<?php
  $id=$_POST['id'];
  echo $id;
  echo "<br>";
  $modelo=$_POST['modelo'];
  echo $modelo;
  echo "<br>";
  $año=$_POST['año'];
  echo $año;
  echo "<br>";
  $chasis=$_POST['$chasis'];
  echo $chasis;
  echo "<br>";
  $motor=$_POST['$motor'];
  echo $motor;
  echo "<br>";
  $propietario=$_POST['propietario'];
  echo $propietario;
  echo "<br>";
  $marca=$_POST['marca'];
  echo $marca;
  echo "<br>";
  $dominio=$_POST['dominio'];
 // echo $dominio;
 // echo "<br>";
 // $periodo=$_POST['periodo'];
 // echo $periodo;
 // echo "<br>";
 // $cuota=$_POST['cuota'];
 // echo $cuota;
 // echo "<br>";
 // $precio=$_POST['precio'];
 // echo $precio;
 // echo "<br>";
 // $direccion=$_POST['direccion'];
 // echo $direccion;
 // echo "<br>";
 // $numero=$_POST['numero'];
 // echo $numero;
 // echo "<br>";
 // $localida=$_POST['localida'];
 // echo $localida;
 // echo "<br>";
 // $codigo=$_POST['codigo'];
 // echo $codigo;
 // echo "<br>";
 // $barra=$_POST['barra'];
 // echo $barra;
 // echo "<br>";  
?>